### ISSUE TITLE
The script fails due to PHP 7.2 dependencies

### ISSUE THREAD

**Issue by enoch85** [iliarostovtsev/webmin-virtualmin-ubuntu20-dev#1]
Great script!

I tried it yesterday in the new Nextcloud VM Ubuntu 20.04. It failed installing LAMP since it was trying to install PHP 7.2, while only 7.4 exists in Ubuntu 20.04. Sure, an easy script change, but still.

Also, why forcing users to install LAMP or LEMP? The only thing I need here is Webmin, no DB needed for that, and instead of forcing the installation of all dependencies - check if they already exists (fulfill the requirement) or install them if they're not. That's how we do in the Nextcloud VM. Just an advice.

Thanks again!

**Comment by iliarostovtsev** [comment]
Hi,

Correct. You don't need Virtualmin install script to install Webmin. Simply install dummy `python` package (according to readme) and install Webmin package manually.

**Comment by enoch85** [comment]
Aah, missed that. 

Will try again.
